version: "3.9"

services:
  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile
    container_name: docs
    volumes:
      - docs_volume:/home/app/docs

  backend:
    container_name: backend
    build: backend
    command: gunicorn projoint.wsgi:application --timeout 120 --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - docs_volume:/home/app/web/docs
    ports:
      - 8000:8000
    depends_on:
      - docs


  frontend:
    container_name: frontend
    build: frontend
    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    build: nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 443:443
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
  media_volume:
  docs_volume:
