name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Pull and Deploy Docker Containers Using Password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} # IP address of the server
        username: ${{ secrets.USERNAME }} # Username given by IT Team
        password: ${{ secrets.PASSWORD }} # Password given by IT Team
        port: ${{ secrets.PORT }} # Port number of the server
        script: |
          cd projointdesigntool
          git pull origin main
          docker compose down
          docker rmi $(docker images -q)
          docker compose up -d
